name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name : Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} ${{secrets.DOCKER_PASSWORD}} --password-stdin
      - name: Build docker image
        run: docker build -t bikashshah15/awsproject .
      - name: Publish image to docker
        run: docker push bikashshah15/awsproject:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull bikashshah15/awsproject:latest
      - name: Delete old container
        run: docker rm -f awsproject || true
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name awsproject bikashshah15/awsproject


